import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/svg1.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-indigo-900 via-indigo-800 to-sky-900">
        <Navbar />

        <div className="flex min-h-[calc(100vh-4rem)]">
          <Sidebar />
          <main className="flex-1  bg-gradient-to-br from-indigo-950 via-indigo-900 to-sky-950">
            {children}
          </main>
        </div>

        <Footer />
      </body>
    </html>
  );
}
